apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels: 
        app: backend-pod
    spec:
      containers:
      - name: backend
        image: 199chennuo/eatornot
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
